/**
 * Tournament creation  (POST /api/tournaments)
 *
 * An organiser submits a tournament name, format, number of rounds,
 * and an initial list of players. On success they receive:
 *   - id          — the public tournament identifier (shared with players)
 *   - adminToken  — a secret token required for all admin operations
 *
 * The admin token is generated server-side with nanoid(16) and is never
 * derivable from the public ID.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { NextRequest } from 'next/server'

vi.mock('@/lib/prisma', () => ({
  prisma: {
    tournament: {
      create: vi.fn(),
    },
  },
}))

import { prisma } from '@/lib/prisma'
import { POST } from './route'

// ─── Request helpers ──────────────────────────────────────────────────────────

function createTournamentRequest(body: unknown) {
  return new NextRequest('http://localhost/api/tournaments', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: { 'Content-Type': 'application/json' },
  })
}

const twoPlayers = [{ name: 'Alice' }, { name: 'Bob' }]

beforeEach(() => vi.clearAllMocks())

// ─── Successful creation ──────────────────────────────────────────────────────

describe('Successful tournament creation', () => {
  it('returns the new tournament ID and a 16-character admin token', async () => {
    vi.mocked(prisma.tournament.create).mockResolvedValueOnce({ id: 'abc12345' } as any)

    const response = await POST(createTournamentRequest({
      name: 'Spring Classic',
      format: 'swiss',
      numRounds: 3,
      players: twoPlayers,
    }))
    const body = await response.json()

    expect(response.status).toBe(200)
    expect(body.id).toBe('abc12345')
    // The admin token is generated by nanoid(16) and is not predictable,
    // but it must always be a 16-character string
    expect(typeof body.adminToken).toBe('string')
    expect(body.adminToken).toHaveLength(16)
  })

  it('assigns sequential seed numbers to players in the order they are submitted', async () => {
    vi.mocked(prisma.tournament.create).mockResolvedValueOnce({ id: 'x' } as any)

    await POST(createTournamentRequest({
      name: 'Cup',
      format: 'swiss',
      numRounds: 3,
      players: [
        { name: 'Alice', rating: 2000 },
        { name: 'Bob',   rating: null  },
        { name: 'Carol'                },
      ],
    }))

    const { data } = vi.mocked(prisma.tournament.create).mock.calls[0][0]
    expect(data.players.create[0]).toMatchObject({ name: 'Alice', rating: 2000, seed: 1 })
    expect(data.players.create[1]).toMatchObject({ name: 'Bob',   rating: null,  seed: 2 })
    expect(data.players.create[2]).toMatchObject({ name: 'Carol', seed: 3 })
  })

  it('trims leading and trailing whitespace from the tournament name', async () => {
    vi.mocked(prisma.tournament.create).mockResolvedValueOnce({ id: 'x' } as any)

    await POST(createTournamentRequest({
      name: '   Spring Classic   ',
      format: 'swiss',
      numRounds: 3,
      players: twoPlayers,
    }))

    const { data } = vi.mocked(prisma.tournament.create).mock.calls[0][0]
    expect(data.name).toBe('Spring Classic')
  })
})

// ─── Format handling ──────────────────────────────────────────────────────────

describe('Tournament format handling', () => {
  it('stores the format exactly as provided when it is "swiss", "rr", or "drr"', async () => {
    vi.mocked(prisma.tournament.create).mockResolvedValue({ id: 'x' } as any)

    for (const format of ['swiss', 'rr', 'drr']) {
      vi.clearAllMocks()
      await POST(createTournamentRequest({ name: 'Cup', format, numRounds: 3, players: twoPlayers }))
      const { data } = vi.mocked(prisma.tournament.create).mock.calls[0][0]
      expect(data.format).toBe(format)
    }
  })

  it('falls back to "swiss" when an unrecognised format is submitted', async () => {
    vi.mocked(prisma.tournament.create).mockResolvedValueOnce({ id: 'x' } as any)

    await POST(createTournamentRequest({
      name: 'Cup',
      format: 'elimination', // not a supported format
      numRounds: 3,
      players: twoPlayers,
    }))

    const { data } = vi.mocked(prisma.tournament.create).mock.calls[0][0]
    expect(data.format).toBe('swiss')
  })
})

// ─── Validation ───────────────────────────────────────────────────────────────

describe('Input validation', () => {
  it('rejects a request with an empty tournament name', async () => {
    const response = await POST(createTournamentRequest({
      name: '',
      format: 'swiss',
      numRounds: 3,
      players: twoPlayers,
    }))

    expect(response.status).toBe(400)
    expect(vi.mocked(prisma.tournament.create)).not.toHaveBeenCalled()
  })

  it('rejects a request with a whitespace-only tournament name', async () => {
    const response = await POST(createTournamentRequest({
      name: '   ',
      format: 'swiss',
      numRounds: 3,
      players: twoPlayers,
    }))

    expect(response.status).toBe(400)
  })

  it('rejects a request with only one player', async () => {
    const response = await POST(createTournamentRequest({
      name: 'Cup',
      format: 'swiss',
      numRounds: 3,
      players: [{ name: 'Alice' }],
    }))

    expect(response.status).toBe(400)
  })

  it('rejects a request with no players at all', async () => {
    const response = await POST(createTournamentRequest({
      name: 'Cup',
      format: 'swiss',
      numRounds: 3,
      players: [],
    }))

    expect(response.status).toBe(400)
  })
})
